import { Course } from "../interfaces/iCourse";

export const mockCourses: Course[] = [
    {
        id: 1,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Intermediate',
        assigned: true,
        isLive: true,
        enrollmentCount: 520,
        rating: 4.90,
        title: 'Angular Fundamentals: Build Your First App',
        description: 'Master the basics of Angular, components, data binding, and routing to kickstart your web development journey.',
        startDate: '10 Jul 2025',
        endDate: '25 Aug 2025',
        durationHours: 10,
        progress: 100,
        amount: 200
      },
      {
        id: 2,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Beginner',
        assigned: false,
        isLive: false,
        enrollmentCount: 1200,
        rating: 4.75,
        title: 'Introduction to Web Development with HTML, CSS, JS',
        description: 'Learn the foundational languages of the web to create your first static websites.',
        startDate: '01 Aug 2025',
        endDate: '15 Sep 2025',
        durationHours: 8,
        progress: 0,
        amount: 200
      },
      {
        id: 3,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Advanced',
        assigned: true,
        isLive: true,
        enrollmentCount: 300,
        rating: 4.95,
        title: 'Full-Stack Development with Node.js and Express',
        description: 'Build robust backend APIs and connect them to your frontend applications using Node.js and Express.js.',
        startDate: '20 Jul 2025',
        endDate: '30 Sep 2025',
        durationHours: 15,
        progress: 40,
        amount: 200
      },
      {
        id: 4,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Intermediate',
        assigned: false,
        isLive: false,
        enrollmentCount: 800,
        rating: 4.60,
        title: 'Understanding Databases: SQL and NoSQL',
        description: 'Explore the differences between relational and non-relational databases and learn when to use each.',
        startDate: '05 Aug 2025',
        endDate: '20 Oct 2025',
        durationHours: 6,
        progress: 0,
        amount: 200
      },
      {
        id: 5,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Beginner',
        assigned: true,
        isLive: true,
        enrollmentCount: 750,
        rating: 4.80,
        title: 'Python for Data Science: Basics to Visualization',
        description: 'Kickstart your data science journey with Python, covering data manipulation, analysis, and visualization.',
        startDate: '15 Jul 2025',
        endDate: '25 Sep 2025',
        durationHours: 12,
        progress: 90,
        amount: 200
      },
      {
        id: 6,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Intermediate',
        assigned: false,
        isLive: true,
        enrollmentCount: 600,
        rating: 4.50,
        title: 'Introduction to Cloud Computing with AWS',
        description: 'Get familiar with Amazon Web Services (AWS) fundamental concepts and core services.',
        startDate: '01 Sep 2025',
        endDate: '15 Oct 2025',
        durationHours: 7,
        progress: 0,
        amount: 200
      },
      {
        id: 7,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Advanced',
        assigned: true,
        isLive: false,
        enrollmentCount: 250,
        rating: 4.98,
        title: 'Microservices Architecture with Docker & Kubernetes',
        description: 'Design, build, and deploy scalable microservices using Docker containers and Kubernetes orchestration.',
        startDate: '10 Aug 2025',
        endDate: '30 Nov 2025',
        durationHours: 20,
        progress: 60,
        amount: 200
      },
      {
        id: 8,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Beginner',
        assigned: false,
        isLive: true,
        enrollmentCount: 950,
        rating: 4.40,
        title: 'Foundations of Cybersecurity',
        description: 'Understand basic cybersecurity principles, threats, and defensive measures.',
        startDate: '01 Jul 2025',
        endDate: '10 Aug 2025',
        durationHours: 5,
        progress: 0,
        amount: 200
      },
      {
        id: 9,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Intermediate',
        assigned: true,
        isLive: true,
        enrollmentCount: 400,
        rating: 4.70,
        title: 'React Native for Mobile App Development',
        description: 'Build cross-platform mobile applications for iOS and Android using React Native.',
        startDate: '05 Sep 2025',
        endDate: '20 Dec 2025',
        durationHours: 18,
        progress: 0,
        amount: 200
      },
      {
        id: 10,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Advanced',
        assigned: false,
        isLive: false,
        enrollmentCount: 150,
        rating: 4.90,
        title: 'Machine Learning with TensorFlow.js',
        description: 'Implement machine learning models directly in the browser using TensorFlow.js.',
        startDate: '15 Oct 2025',
        endDate: '30 Jan 2026',
        durationHours: 12,
        progress: 0,
        amount: 200
      },
      {
        id: 11,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Beginner',
        assigned: true,
        isLive: true,
        enrollmentCount: 600,
        rating: 4.85,
        title: 'Vue.js Mastery: The Progressive Framework',
        description: 'Learn to build dynamic single-page applications with the Vue.js framework.',
        startDate: '01 Aug 2025',
        endDate: '15 Oct 2025',
        durationHours: 11,
        progress: 55,
        amount: 200
      },
      {
        id: 12,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Intermediate',
        assigned: false,
        isLive: false,
        enrollmentCount: 700,
        rating: 4.55,
        title: 'Git & GitHub: Version Control for Developers',
        description: 'Essential skills for collaborating on projects and managing code changes effectively.',
        startDate: '10 Sep 2025',
        endDate: '05 Nov 2025',
        durationHours: 4,
        progress: 0,
        amount: 200
      },
      {
        id: 13,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Advanced',
        assigned: true,
        isLive: true,
        enrollmentCount: 200,
        rating: 4.92,
        title: 'Advanced Data Structures and Algorithms',
        description: 'Strengthen your problem-solving skills with complex data structures and efficient algorithms.',
        startDate: '20 Sep 2025',
        endDate: '28 Feb 2026',
        durationHours: 25,
        progress: 88,
        amount: 200
      },
      {
        id: 14,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Beginner',
        assigned: false,
        isLive: true,
        enrollmentCount: 1100,
        rating: 4.30,
        title: 'Introduction to UI/UX Design',
        description: 'Discover the fundamentals of user interface and user experience design principles.',
        startDate: '01 Jul 2025',
        endDate: '10 Aug 2025',
        durationHours: 6,
        progress: 0,
        amount: 200
      },
      {
        id: 15,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Intermediate',
        assigned: true,
        isLive: false,
        enrollmentCount: 350,
        rating: 4.65,
        title: 'Testing Angular Applications: Unit & Integration',
        description: 'Learn to write comprehensive tests for your Angular applications using Karma, Jasmine, and Protractor.',
        startDate: '01 Nov 2025',
        endDate: '15 Jan 2026',
        durationHours: 9,
        progress: 25,
        amount: 200
      },
      {
        id: 16,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Beginner',
        assigned: false,
        isLive: false,
        enrollmentCount: 900,
        rating: 4.20,
        title: 'Basic JavaScript: From Variables to Functions',
        description: 'A solid introduction to JavaScript, the language of the web, for absolute beginners.',
        startDate: '10 Aug 2025',
        endDate: '20 Sep 2025',
        durationHours: 7,
        progress: 0,
        amount: 200
      },
      {
        id: 17,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Advanced',
        assigned: true,
        isLive: true,
        enrollmentCount: 180,
        rating: 4.99,
        title: 'DevOps CI/CD Pipelines with Jenkins & GitLab CI',
        description: 'Automate your software delivery process with continuous integration and continuous deployment.',
        startDate: '25 Jul 2025',
        endDate: '05 Nov 2025',
        durationHours: 22,
        progress: 70,
        amount: 200
      },
      {
        id: 18,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Intermediate',
        assigned: false,
        isLive: false,
        enrollmentCount: 550,
        rating: 4.50,
        title: 'Responsive Web Design with Bootstrap 5',
        description: 'Build beautiful, mobile-first websites using the latest version of Bootstrap.',
        startDate: '01 Oct 2025',
        endDate: '15 Nov 2025',
        durationHours: 8,
        progress: 0,
        amount: 200
      },
      {
        id: 19,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Beginner',
        assigned: true,
        isLive: true,
        enrollmentCount: 850,
        rating: 4.70,
        title: 'C# Programming for Absolute Beginners',
        description: 'Learn the fundamentals of C# programming, a versatile language for various applications.',
        startDate: '01 Jul 2025',
        endDate: '30 Sep 2025',
        durationHours: 14,
        progress: 100,
        amount: 200
      },
      {
        id: 20,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Intermediate',
        assigned: false,
        isLive: true,
        enrollmentCount: 480,
        rating: 4.60,
        title: 'Data Visualization with D3.js',
        description: 'Create compelling and interactive data visualizations using the D3.js library.',
        startDate: '15 Sep 2025',
        endDate: '30 Nov 2025',
        durationHours: 10,
        progress: 0,
        amount: 200
      },
      {
        id: 21,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Advanced',
        assigned: true,
        isLive: false,
        enrollmentCount: 100,
        rating: 4.95,
        title: 'Advanced TypeScript: Generics & Decorators',
        description: 'Master advanced TypeScript features to write more robust and maintainable code.',
        startDate: '01 Nov 2025',
        endDate: '28 Feb 2026',
        durationHours: 16,
        progress: 15,
        amount: 200
      },
      {
        id: 22,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Beginner',
        assigned: false,
        isLive: false,
        enrollmentCount: 1500,
        rating: 4.10,
        title: 'Digital Literacy: Essential Computer Skills',
        description: 'Fundamental skills for navigating the digital world, perfect for beginners.',
        startDate: '05 Jul 2025',
        endDate: '20 Aug 2025',
        durationHours: 4,
        progress: 0,
        amount: 200
      },
      {
        id: 23,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Intermediate',
        assigned: true,
        isLive: true,
        enrollmentCount: 650,
        rating: 4.88,
        title: 'Vuex State Management in Vue.js',
        description: 'Manage application state efficiently in large Vue.js applications using Vuex.',
        startDate: '20 Aug 2025',
        endDate: '10 Nov 2025',
        durationHours: 12,
        progress: 65,
        amount: 200
      },
      {
        id: 24,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Advanced',
        assigned: false,
        isLive: false,
        enrollmentCount: 220,
        rating: 4.78,
        title: 'Blockchain for Developers: Concepts & DApps',
        description: 'Understand blockchain technology and build decentralized applications.',
        startDate: '01 Dec 2025',
        endDate: '31 Mar 2026',
        durationHours: 18,
        progress: 0,
        amount: 200
      },
      {
        id: 25,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Beginner',
        assigned: true,
        isLive: true,
        enrollmentCount: 700,
        rating: 4.80,
        title: 'Getting Started with Spring Boot',
        description: 'Develop powerful, production-ready Spring applications with minimal fuss.',
        startDate: '10 Jul 2025',
        endDate: '20 Sep 2025',
        durationHours: 13,
        progress: 85,
        amount: 200
      },
      {
        id: 26,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Intermediate',
        assigned: false,
        isLive: false,
        enrollmentCount: 500,
        rating: 4.45,
        title: 'Advanced Excel for Data Analysis',
        description: 'Unlock the power of Excel for complex data analysis, pivot tables, and macros.',
        startDate: '01 Nov 2025',
        endDate: '15 Dec 2025',
        durationHours: 7,
        progress: 0,
        amount: 200
      },
      {
        id: 27,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Advanced',
        assigned: true,
        isLive: true,
        enrollmentCount: 170,
        rating: 4.97,
        title: 'Scalable Database Design with PostgreSQL',
        description: 'Design and optimize robust database schemas for high-performance applications.',
        startDate: '15 Aug 2025',
        endDate: '30 Nov 2025',
        durationHours: 19,
        progress: 50,
        amount: 200
      },
      {
        id: 28,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Beginner',
        assigned: false,
        isLive: true,
        enrollmentCount: 1050,
        rating: 4.25,
        title: 'Introduction to Figma for UI Design',
        description: 'Learn the basics of Figma, a powerful tool for designing user interfaces.',
        startDate: '01 Oct 2025',
        endDate: '15 Nov 2025',
        durationHours: 5,
        progress: 0,
        amount: 200
      },
      {
        id: 29,
        image: '/assets/img/auth_background.png',
        type: 'Paid',
        level: 'Intermediate',
        assigned: true,
        isLive: false,
        enrollmentCount: 420,
        rating: 4.68,
        title: 'State Management with NgRx in Angular',
        description: 'Implement robust and predictable state management in Angular using the NgRx library.',
        startDate: '20 Nov 2025',
        endDate: '28 Feb 2026',
        durationHours: 14,
        progress: 30,
        amount: 200
      },
      {
        id: 30,
        image: '/assets/img/auth_background.png',
        type: 'Free',
        level: 'Advanced',
        assigned: false,
        isLive: false,
        enrollmentCount: 90,
        rating: 4.80,
        title: 'Deep Learning with Keras and TensorFlow',
        description: 'Build and train neural networks for various AI applications using Keras and TensorFlow.',
        startDate: '01 Jan 2026',
        endDate: '30 Apr 2026',
        durationHours: 20,
        progress: 0,
        amount: 200
      }
    ]